### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yekayee** [K1utzer/Chess.com-bot#11]
Traceback (most recent call last):
  File "C:\laragon\www\Chess.com-bot\bot\Manager.py", line 260, in detect_board
    boardFound, self.board_coordinates, self.field_height, self.field_width, self.board_height, self.board_width = imageDet.searchBoard(
  File "C:\laragon\www\Chess.com-bot\bot\ImageDetection.py", line 28, in searchBoard
    board_result1 = cv.matchTemplate(
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

**Comment by K1utzer** [comment]
working on a rework of the bot, which should also fix this problem
