### ISSUE TITLE
configparser.NoSectionError: No section: 'chess.com'

### ISSUE THREAD

**Issue by mela-nen** [K1utzer/Chess.com-bot#4]
After fixing the cofig file and doing everything, it returns this error, what should i do?

**Comment by lutzwolfer** [comment]
What do mean with fixing the config file? In the config.cfg should only be the [stockfish] section as the script is only looking after that.

**Comment by mela-nen** [comment]
yes, that's what i meant, even when I have chess.com opened on a game, it still says "configparser.NoSectionError: No section: 'chess.com'"

**Comment by lutzwolfer** [comment]
Check out the master branch, it should work with that version

**Comment by mela-nen** [comment]
just did that, firefox opened but after log in, it doesnt do anything, here's the error
 DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  elements = driver.find_elements_by_class_name('live-game-over-component')

**Comment by lutzwolfer** [comment]
Download the 'master' branch and the issue will be fixxed

**Comment by lutzwolfer** [comment]
You're using a outdated version
