### ISSUE TITLE
need help too bc dumb

### ISSUE THREAD

**Issue by EssBDub** [K1utzer/Chess.com-bot#8]
well i got this so :P
![Screenshot 2022-06-20 010142](https://user-images.githubusercontent.com/67671044/174528598-e3a6ae65-da11-487e-a436-9b0ec1ccb564.png)

**Comment by lutzwolfer** [comment]
Start the bot with: python -m bot.py

**Comment by EssBDub** [comment]
> 

you mean like this ._.
![Screenshot 2022-06-20 011810](https://user-images.githubusercontent.com/67671044/174530286-6f4edf4c-dc09-47e5-8eb7-a8fcdfe99e80.png)

**Comment by lutzwolfer** [comment]
python -m bot. Sorry my fault, without the .py

**Comment by EssBDub** [comment]
well i see where your coming from but at the same time i dont :P
![Screenshot 2022-06-20 012405](https://user-images.githubusercontent.com/67671044/174530854-b4f3d856-5bba-44d7-87b8-9ea7cfae216a.png)

**Comment by lutzwolfer** [comment]
Try: pip install -r requirements.txt first

**Comment by EssBDub** [comment]
everything is now satisfied and it says this 
![Screenshot 2022-06-20 013303](https://user-images.githubusercontent.com/67671044/174531758-f89491d5-ce13-41c7-b4f7-9265b0944ced.png)

**Comment by me-rgb** [comment]
py -m pip install PyQt5

**Comment by EssBDub** [comment]
it loaded thxs so much

**Comment by FordPress** [comment]
I have this error

![image](https://user-images.githubusercontent.com/110938319/186284079-d78d1829-70de-4afa-84cd-b38f7fcb780d.png)
